//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CO5027OnlineShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class productsTable
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string Price { get; set; }
        public string ProductInformation { get; set; }
        public string ScreenSize { get; set; }
        public string Resolution { get; set; }
        public string EnergyEfficiencyClass { get; set; }
        public string SmartTV { get; set; }
        public string Stock { get; set; }
    }
}
